[tool.poetry]
name = "poi"
version = "0.1.0"
description = ""
authors = ["Ryan Wang <hwwangwang@gmail.com>"]
include = ["poi/templates/", "poi/static/"]


[tool.poetry.dependencies]
python = "^3.7"
lazy_object_proxy = "^1.3"
flask = "^1.0"
flask_sqlalchemy = "^2.3"
flask_migrate = "^2.3"
ipython = "^7.2"
python-dotenv = "^0.10.0"
pyjwt = "^1.7"
voluptuous = "^0.11.5"
pymysql = "^0.9.3"
gunicorn = "^19.9"
flask_mail = "^0.9.1"
pandas = "^0.23.4"
xlrd = "^1.2"
requests = "^2.21"
xlsxwriter = "^1.1"
typing_extensions = "^3.7"


[tool.poetry.dev-dependencies]
flake8 = "^3.6"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
mypy = "^0.660"
pytest = "^4.0"
fabric = "^2.4"
sqlalchemy-stubs = { git = "https://github.com/dropbox/sqlalchemy-stubs.git", branch = "master" }


[tool.black]
py36 = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


